import { MiniPlayer } from "miniplayer/MiniPlayer.slint";
import { StandardButton } from "std-widgets.slint";
import { MiniPlayerState } from "miniplayer/State.slint";
import { Sidebar } from "sidebar/Sidebar.slint";

export component MainWindow inherits Window {
    background: #000000;
    width: 1440px;
    height: 1040px;

    sidebar := Sidebar {
        x: 0px;
        y: 0px;
        height: miniplayer.y;
    }

    miniplayer := MiniPlayer {
        width: parent.width;
        y: parent.height - self.height;
    }
}
