import { SidebarTheme } from "Theme.slint";
import { SidebarState } from "State.slint";

export component SidebarIcon {
    width: 22px;
    height: 22px;

    in property <bool> is-selected: false;
    in property <string> commands-default;
    in property <string> commands-selected;

    Path {
        viewbox-width: 22;
        viewbox-height: 22;

        fill: SidebarTheme.iconColorDefault;
        stroke: transparent;
        stroke-width: 0px;

        commands: commands-default;
        opacity: is-selected ? 0.0 : 1.0;

        animate opacity {
            duration: 200ms;
            easing: ease-in-out;
        }

        states [
            selected when is-selected: {
                fill: SidebarTheme.iconColorSelected;
                commands: commands-selected;
                in {
                    animate fill {
                        duration: 300ms;
                        easing: ease-in-out;
                    }
                }
                out {
                    animate fill {
                        duration: 300ms;
                        easing: ease-in-out;
                    }
                }
            }
        ]
    }

    Path {
        viewbox-width: 22;
        viewbox-height: 22;
        fill: SidebarTheme.iconColorSelected;
        commands: commands-selected;
        opacity: is-selected ? 1.0 : 0.0;
        animate opacity {
            duration: 300ms;
            easing: ease-in-out;
        }
    }
}

export component SidebarButton {
    in property <string> label;
    in property <int> index;
    in-out property <int> selected-index;
    private property <bool> active: selected-index == index;
    in property <string> icon-commands-default;
    in property <string> icon-commands-selected;

    callback clicked();

    width: 180px;
    height: 40px;

    ta := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: MouseCursor.pointer;

        clicked => {
            root.clicked();
            selected-index = index;
        }
    }

    container := Rectangle {
        width: parent.width;
        height: parent.height;
        border-radius: 5px;

        background: active ? SidebarTheme.backgroundButtonSelected : ta.has-hover ? SidebarTheme.backgroundButtonHover : transparent;

        animate background { duration: 200ms; }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                alignment: start;
                spacing: 15px;
                padding-left: 20px;
                padding-right: 20px;

                SidebarIcon {
                    is-selected: root.active;
                    commands-default: root.icon-commands-default;
                    commands-selected: root.icon-commands-selected;
                }

                Text {
                    text: label;
                    font-size: 16px;
                    vertical-alignment: center;
                }
            }
        }
    }
}
