component IconBase inherits TouchArea {
    width: 32px;
    height: 32px;

    in property <bool> is-filled: true;
    in property <string> commands;

    mouse-cursor: pointer;

    Path {
        viewbox-width: 24;
        viewbox-height: 24;

        fill: is-filled ? #FFF : transparent;
        stroke: is-filled ? transparent : #FFF;
        stroke-width: 2.3px;

        animate fill, stroke { duration: 100ms; }

        commands: commands;
    }
}

export component LikeIcon inherits IconBase {
    commands: "M15 8h2.4a4 4 0 0 1 3.94 4.72l-.9 5A4 4 0 0 1 16.5 21H8V9l1.82-5.79a1.84 1.84 0 0 1 2.02-1.13C13.37 2.38 15 3.57 15 5.5zM6 9a3 3 0 0 0-3 3v6a3 3 0 0 0 3 3z";
}

export component DislikeIcon inherits IconBase {
    commands: "M15 16h2.4a4 4 0 0 0 3.94-4.72l-.9-5A4 4 0 0 0 16.5 3H8v12l1.82 5.79c.3.69 1.06 1.31 2.02 1.13 1.53-.3 3.16-1.49 3.16-3.42zm-9-1a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3z";
}
