import { SongInfo } from "SongInfo.slint";
import { MiniPlayerState } from "State.slint";
import { PlaybackControls } from "PlaybackControls.slint";
import { MiniplayerTheme } from "Theme.slint";
import { Timeline } from "Timeline.slint";
import { Volume } from "Volume.slint";
import { Options } from "Options.slint";

export component MiniPlayer {
    height: 75px;

    Timeline {
        width: parent.width;
        height: parent.height;
    }

    VerticalLayout {
        y: 3px;
        height: 70px;

        padding-left: 10px;
        padding-right: 10px;
        alignment: center;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                width: 40%;

                SongInfo { }
            }

            HorizontalLayout {
                alignment: center;

                PlaybackControls { }
            }

            VerticalLayout {
                width: 40%;
                alignment: center;

                HorizontalLayout {
                    alignment: end;
                    padding-right: 10px;

                    Volume { }

                    Options { }
                }
            }
        }
    }

    states [
        listening when MiniPlayerState.listening: {
            y: 0px;
            in {
                animate y {
                    duration: 200ms;
                    easing: ease-out;
                }
            }
        }
        not-listening when !MiniPlayerState.listening: {
            y: root.height;
            in {
                animate y {
                    duration: 200ms;
                    easing: ease-in;
                }
            }
        }
    ]
}
