export global MiniplayerTheme {
    in property <brush> timeline-bg: #111;
    in property <brush> timeline-loaded: #444;
    in property <brush> timeline-progress: @linear-gradient(90deg, #59EFEC, #0B747A);
    in property <brush> timeline-thumb: #0B747A;

    in property <brush> timeline-tooltip: #47D;
    in property <brush> timeline-tooltip-text: #FFF;

    in property <brush> volume-track: #BBB;
    in property <brush> volume-progress: #FFF;
    in property <brush> volume-thumb: #FFF;

    in property <length> song-cover-radius: 8px;
    in property <brush> song-title: #FFF;
    in property <brush> song-artist: #888;
}
